/*SUMAR 0,2 A TODOS LOS ARTICULOS QUE VALEN MENOS DE 1€*/
UPDATE Articulo
SET PVPArt = PVPArt + 0.2
WHERE PVPArt < 1;
/*ACTUALIZAR LA FECHA DEL PEDIDO P0001 a 2024-02-29*/
UPDATE Pedido
SET FecPed = '2024-02-29'
WHERE RefPed = 'P0001';
/*BORRAR LOS ARTICULOS QUE TENGAN UN PRECIO SUPERIOR A 1€*/
DELETE FROM LineaPedido
WHERE CodArt='A0078';
DELETE FROM Articulo
WHERE PVPArt > 1;
/*CAMBIAR EL TIPO DE DATO DE CANTART PARA QUE TENGA DOS DECIMALES*/
ALTER TABLE LineaPedido
MODIFY COLUMN CantArt DECIMAL(5, 2) NOT NULL;
/*AUMENTAR LA CANTIDAD DE PRODUCTOS QUE FORMAN PARTE DEL PEDIDO P0004 EN 5 UNIDADES CADA UNO*/
UPDATE LineaPedido
SET CantArt = CantArt + 5
WHERE RefPed = 'P0004';
/*IMPEDIR QUE EL PVPART SEA INFERIOR A 0*/
ALTER TABLE Articulo
ADD CONSTRAINT Pre_min
CHECK (PVPArt>=0);