/* MODELO RELACIONAL:
PROVEEDORES (Codigo(PK), Nombre, Direccion, Ciudad, Provincia)
PROVEEDORES_PIEZAS (Codigo(FK), CodigoP(FK), Cantidad, Fecha)
PIEZAS (CodigoP(PK), Nombre, Precio, Color)
CATEGORIAS(CodigoC(PK), Nombre)
*/

/*1.CREACION DE LAS TABLAS*/
CREATE TABLE PROVEEDORES(
    Codigo VARCHAR(9) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Direccion VARCHAR(100) NOT NULL,
    Ciudad VARCHAR(50) NOT NULL,
    Provincia VARCHAR(50)
);

CREATE TABLE PIEZAS(
    CodigoP VARCHAR(9) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Precio DECIMAL (7,2) NOT NULL,
    Color VARCHAR (20) NOT NULL
);

CREATE TABLE CATEGORIAS(
    CodigoC VARCHAR(9) NOT NULL,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE PROVEEDORES_PIEZAS(
    Codigo VARCHAR(9) NOT NULL
    Codigop VARCHAR(9) NOT NULL
    Cantidad INT,
    Fecha DATE NOT NULL
);

/*2. CREACION DE LAS CLAVES PRIMARIAS*/
ALTER TABLE PROVEEDORES
ADD CONSTRAINT pk_proveedores PRIMARY KEY (Codigo);

ALTER TABLE PIEZAS
ADD CONSTRAINT pk_piezas PRIMARY KEY (CodigoP);

ALTER TABLE CATEGORIAS
ADD CONSTRAINT pk_categorias PRIMARY KEY (CodigoC);

/*CREACION DE LAS CLAVES FORANEAS*/
ALTER TABLE PROVEEDORES_PIEZAS
ADD CONSTRAINT fk_proveedor_codigo FOREIGN KEY (Codigo) REFERENCES PROVEEDORES (Codigo),
ADD CONSTRAINT fk_piezas_codigoP FOREIGN KEY (CodigoP) REFERENCES PIEZAS (CodigoP);
